/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jmteamconsulting.SGPS.view;

import com.jmteamconsulting.SGPS.controller.ControladorUsuario;
import com.jmteamconsulting.SGPS.model.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ianpineda
 */
public class PanelRaiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelRaiz.class.getName());

    /**
     * Creates new form PanelRaiz
     */
    public PanelRaiz() {        
        initComponents();

        this.PESTANA_CREAR_CAMPOS_DE_ENTRADA = new javax.swing.JTextField[] {
            jTextFieldCiudad,
            jTextFieldCodigoZIP,
            jTextFieldDepartamento,
            jTextFieldDireccionPrimeraLinea,
            jTextFieldDireccionSegundaLinea,
            jTextFieldEmail,
            jTextFieldNumeroDocumento,
            jTextFieldPais,
            jTextFieldPrimerApellido,
            jTextFieldPrimerNombre,
            jTextFieldSegundoApellido,
            jTextFieldSegundoNombre,
            jTextFieldTelefono,
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelNumeroDocumento = new javax.swing.JLabel();
        jTextFieldNumeroDocumento = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPrimerNombre = new javax.swing.JLabel();
        jTextFieldPrimerNombre = new javax.swing.JTextField();
        jLabelSegundoNombre = new javax.swing.JLabel();
        jTextFieldSegundoNombre = new javax.swing.JTextField();
        jLabelPrimerApellido = new javax.swing.JLabel();
        jTextFieldPrimerApellido = new javax.swing.JTextField();
        jLabelSegundoApellido = new javax.swing.JLabel();
        jTextFieldSegundoApellido = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabelDepartamento = new javax.swing.JLabel();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jLabelCiudad = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabelDireccionPrimeraLinea = new javax.swing.JLabel();
        jTextFieldDireccionPrimeraLinea = new javax.swing.JTextField();
        jLabelDireccionSegundaLinea = new javax.swing.JLabel();
        jTextFieldDireccionSegundaLinea = new javax.swing.JTextField();
        jLabelCodigoZIP = new javax.swing.JLabel();
        jTextFieldCodigoZIP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonBorrarTodo = new javax.swing.JButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabelEliminar = new javax.swing.JLabel();
        jTextFieldIDEliminar = new javax.swing.JTextField();
        jButtonEliminarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 8, 16));
        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(null);
        jPanel1.setLayout(new java.awt.GridLayout(15, 2, 16, 4));

        jLabelNumeroDocumento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumeroDocumento.setLabelFor(jLabelNumeroDocumento);
        jLabelNumeroDocumento.setText("Número de documento:");
        jPanel1.add(jLabelNumeroDocumento);
        jPanel1.add(jTextFieldNumeroDocumento);

        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail.setLabelFor(jLabelEmail);
        jLabelEmail.setText("Email:");
        jPanel1.add(jLabelEmail);
        jPanel1.add(jTextFieldEmail);

        jLabelPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrimerNombre.setLabelFor(jLabelPrimerNombre);
        jLabelPrimerNombre.setText("Primer nombre:");
        jPanel1.add(jLabelPrimerNombre);
        jPanel1.add(jTextFieldPrimerNombre);

        jLabelSegundoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoNombre.setLabelFor(jLabelSegundoNombre);
        jLabelSegundoNombre.setText("Segundo nombre:");
        jPanel1.add(jLabelSegundoNombre);
        jPanel1.add(jTextFieldSegundoNombre);

        jLabelPrimerApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrimerApellido.setLabelFor(jLabelPrimerApellido);
        jLabelPrimerApellido.setText("Primer apellido:");
        jPanel1.add(jLabelPrimerApellido);
        jPanel1.add(jTextFieldPrimerApellido);

        jLabelSegundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoApellido.setLabelFor(jLabelSegundoApellido);
        jLabelSegundoApellido.setText("Segundo apellido:");
        jPanel1.add(jLabelSegundoApellido);
        jPanel1.add(jTextFieldSegundoApellido);

        jLabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTelefono.setLabelFor(jLabelTelefono);
        jLabelTelefono.setText("Teléfono:");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldTelefono);

        jLabelPais.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPais.setLabelFor(jLabelPais);
        jLabelPais.setText("País:");
        jPanel1.add(jLabelPais);
        jPanel1.add(jTextFieldPais);

        jLabelDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDepartamento.setLabelFor(jLabelDepartamento);
        jLabelDepartamento.setText("Departamento");
        jPanel1.add(jLabelDepartamento);
        jPanel1.add(jTextFieldDepartamento);

        jLabelCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCiudad.setLabelFor(jLabelCiudad);
        jLabelCiudad.setText("Ciudad");
        jPanel1.add(jLabelCiudad);
        jPanel1.add(jTextFieldCiudad);

        jLabelDireccionPrimeraLinea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDireccionPrimeraLinea.setLabelFor(jLabelDireccionPrimeraLinea);
        jLabelDireccionPrimeraLinea.setText("Dirección (primera línea):");
        jPanel1.add(jLabelDireccionPrimeraLinea);
        jPanel1.add(jTextFieldDireccionPrimeraLinea);

        jLabelDireccionSegundaLinea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDireccionSegundaLinea.setLabelFor(jLabelDireccionSegundaLinea);
        jLabelDireccionSegundaLinea.setText("Dirección (segunda línea):");
        jPanel1.add(jLabelDireccionSegundaLinea);
        jPanel1.add(jTextFieldDireccionSegundaLinea);

        jLabelCodigoZIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCodigoZIP.setLabelFor(jLabelCodigoZIP);
        jLabelCodigoZIP.setText("Código de área (ZIP):");
        jPanel1.add(jLabelCodigoZIP);
        jPanel1.add(jTextFieldCodigoZIP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        jButtonBorrarTodo.setText("Borrar Todo");
        jButtonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorrarTodo);

        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearUsuario);

        jTabbedPane1.addTab("Crear", null, jPanel1, "");

        jPanel2.setMaximumSize(null);
        jPanel2.setMinimumSize(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Leer", jPanel2);

        jPanel3.setMaximumSize(null);
        jPanel3.setMinimumSize(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Actualizar", jPanel3);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 16, 16));

        jLabelEliminar.setLabelFor(jTextFieldIDEliminar);
        jLabelEliminar.setText("ID de usuario a eliminar:");
        jPanel9.add(jLabelEliminar);

        jTextFieldIDEliminar.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel9.add(jTextFieldIDEliminar);

        jPanel7.add(jPanel9);

        jButtonEliminarUsuario.setText("Eliminar Usuario");
        jButtonEliminarUsuario.setAlignmentX(0.5F);
        jButtonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonEliminarUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jPanel7, gridBagConstraints);

        jTabbedPane1.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método ejecutado al hacer click en el botón Borrar Todo de la pestaña
     * Crear del JFrame principal.
     * 
     * @param evt Evento AWT generado.
     */
    private void jButtonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodoActionPerformed
        for (javax.swing.JTextField campo: this.PESTANA_CREAR_CAMPOS_DE_ENTRADA) {
            campo.setText("");
        }
    }//GEN-LAST:event_jButtonBorrarTodoActionPerformed

    /**
     * Método ejecutado al hacer click en el botón Crear Usuario de la pestaña
     * Crear del JFrame principal.
     * 
     * @param evt Evento AWT generado.
     */
    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        // Se intenta crear un objeto Usuario a partir de los datos ingresados.
        Usuario usuario = new Usuario(
            null, // id
            this.jTextFieldNumeroDocumento.getText(),
            this.jTextFieldEmail.getText(),
            this.jTextFieldPrimerNombre.getText(),
            this.jTextFieldSegundoNombre.getText(),
            this.jTextFieldPrimerApellido.getText(),
            this.jTextFieldSegundoApellido.getText(),
            this.jTextFieldTelefono.getText(),
            this.jTextFieldPais.getText(),
            this.jTextFieldDepartamento.getText(),
            this.jTextFieldCiudad.getText(),
            this.jTextFieldDireccionPrimeraLinea.getText(),
            this.jTextFieldDireccionSegundaLinea.getText(),
            this.jTextFieldCodigoZIP.getText() 
        );
        
        // Se intenta insertar el objeto usuario en la base de datos
        final long id;
        
        try {   
            id = ControladorUsuario.crearUsuario(usuario);
        } catch (SQLException ex) {
            // Error SQL. Se muestra información de la excepción al usuario.
            System.getLogger(PanelRaiz.class.getName()).log(System.Logger.Level.ERROR, "Error creando usuario", ex);
            JOptionPane.showMessageDialog(this, "Error creando usuario:\n\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        // Se muestra mensaje de éxito con el ID del usuario creado.
        JOptionPane.showMessageDialog(this, "Usuario creado exitosamente con un ID de:\n\n" + id, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    /**
     * Handler de click de botón de eliminación de usuario.
     * 
     * @param evt Evento AWT generado.
     */
    private void jButtonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarUsuarioActionPerformed
        // Primero se obtiene el ID ingresado.
        final String idString = this.jTextFieldIDEliminar.getText();
        final long id;
        
        // Se intenta convertir a número entero.
        try {
            id = Long.parseLong(idString);
        } catch (NumberFormatException ex) {
            // Se muestra mensaje de error en caso de haber ocurrido un error.
            System.getLogger(PanelRaiz.class.getName()).log(System.Logger.Level.ERROR, "Error de formato", ex);
            JOptionPane.showMessageDialog(this, "La ID ingresada debe ser un numero entero:\n\n" + ex.getMessage(), "Error de formato", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        // Se intenta eliminar el registro. Se usa executeUpdate para obtener los resultados.
        final int filasEliminadas;
        
        try {   
            filasEliminadas = ControladorUsuario.eliminarUsuario(id);
        } catch (SQLException ex) {
            // Error SQL. Se muestra información de la excepción al usuario.
            System.getLogger(PanelRaiz.class.getName()).log(System.Logger.Level.ERROR, "Error eliminando usuario", ex);
            JOptionPane.showMessageDialog(this, "Error eliminando usuario:\n\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        // Registro eliminado exitosamente. Se le informa al usuario.
        if (filasEliminadas > 0) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Registro no eliminado. Posiblemente el registro no existía.
        System.getLogger(PanelRaiz.class.getName()).log(System.Logger.Level.ERROR, "Error eliminando usuario");
        JOptionPane.showMessageDialog(this, "No pudo el usuario con el ID especificado.\nAsegurese de que existe un usuario con el ID: " + id, "Error de eliminación", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            PanelRaiz raiz = new PanelRaiz();
            raiz.setLocationRelativeTo(null);
            raiz.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarTodo;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonEliminarUsuario;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelCodigoZIP;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDireccionPrimeraLinea;
    private javax.swing.JLabel jLabelDireccionSegundaLinea;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNumeroDocumento;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPrimerApellido;
    private javax.swing.JLabel jLabelPrimerNombre;
    private javax.swing.JLabel jLabelSegundoApellido;
    private javax.swing.JLabel jLabelSegundoNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldCodigoZIP;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldDireccionPrimeraLinea;
    private javax.swing.JTextField jTextFieldDireccionSegundaLinea;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIDEliminar;
    private javax.swing.JTextField jTextFieldNumeroDocumento;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldPrimerApellido;
    private javax.swing.JTextField jTextFieldPrimerNombre;
    private javax.swing.JTextField jTextFieldSegundoApellido;
    private javax.swing.JTextField jTextFieldSegundoNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    private final javax.swing.JTextField[] PESTANA_CREAR_CAMPOS_DE_ENTRADA;
}
